//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmalgamClientTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Dk8NMkEWgSkj1LVDBb8p87f48VL5CUcjwgakYMBlwpP0nVPTFN+1HLzUlvlPP1SidIy8ok3XUMHaeWS0K+/8gNvSgDrpseFPY75GwTxRGf9EBnXiEiENyKhkfPRLR2YzKXEu6UW44oI6k98Y+L+f6PizmXOOkn5UBDh8l0qZeZGYYfAU9jHjZq0RRKymbGV1/bsNxFgdoucRqmgvGEm9OOAryGSaEYpiV74vqM0O/sItO5W69GQJ1/pV+JeuTzpjSSIalCF8gfuO6cuZiNjWsHE7JrqzhYLlnzttpENqLcT20tZ+3hgcBDya83fen+eI2zxAnoEIOgq5hv67DlnLdUu/923kzamfnk4cLupN9mqgQIETGRymEXKxMwzNo44ifD2XPRMul4pK87TvHlj7IPCgIKbbCeUH06IV/dAl1+gnBKa3Q+5V2f9usq5beMl4z7fAoh8TVAZ6e3/YaUahbMGFEY9v10sd8soxqhSBp91GYyH/i5OYHE1HTWFqDIMmApk48jCXFVwSGjiSrM8V/LHC9h+PmP02jO75CAjE+YXT5fKtGRp+qgMBTONWFZMqFxPOg+XEyDzbmbZnasUr1KYWkBX6Pv3kqs8VrSRA7ECH2M9FF6s7aAJobj+it0CPRbld02FZgRn35HlOByzgSNbGd8+VFlEk+KEE77rctwiCSrKbdyE828GbIhl2jnjuIXoNLTqNtzz9cW16xSpMPrhBJLttEESELf/H75z9uZR74NyPQ6E81Mofj8nU6b/u")]
        public string Salt {
            get {
                return ((string)(this["Salt"]));
            }
        }
    }
}
